site_name: giraycoskun.com
site_url: https://giraycoskun.com/
site_author: Giray Coskun
site_description: I am a software engineer and this is my personal website

# Repository
repo_name: giraycoskun/giraycoskun.com
repo_url: https://github.com/giraycoskun/giraycoskun.com

theme:
  language: en 
  name: material
  custom_dir: docs/overrides
  logo: assets/developer.png
  favicon: assets/developer.png
  features:
    - navigation.indexes
    - navigation.top
    - navigation.tabs.sticky
    - content.code.annotate
    - toc.follow
    - content.code.copy
    - navigation.instant
    - navigation.instant.progress

  palette:
    
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/giraycoskun
    - icon: fontawesome/brands/github 
      link: https://github.com/giraycoskun
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/in/giraycoskun/
  

plugins:
    - search
    - macros
    - blog:
        blog_toc: true
        pagination: true
        pagination_per_page: 5
    - tags:
        tags_file: ./blog/tags.md

markdown_extensions:
  - pymdownx.pathconverter:
      base_path: '' # default: ''
      relative_path: 'docs/' # default ''
      absolute: false # default: false
      tags: 'a script img link object embed'
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - My Blog:
    - blog/index.md
    - blog/tags.md
  - Developer Website: https://giraycoskun.com/
  - GitHub Projects: https://giraycoskun.github.io/
